import { NextResponse } from 'next/server';

export const initialGeoCodes = {
 'FR - France': 'Not Allocated',
  'GB - United Kingdom': 'Not Allocated',
  'DE - Germany': 'Not Allocated',
  'NL - Netherlands': 'Not Allocated',
  'US - United States': 'Not Allocated',
  'CA - Canada': 'Not Allocated',
  'AU - Australia': 'Not Allocated',
  'NZ - New Zealand': 'Not Allocated',
  'JP - Japan': 'Not Allocated',
  'CN - China': 'Not Allocated',
  'IN - India': 'Not Allocated',
  'BR - Brazil': 'Not Allocated',
  'RU - Russia': 'Not Allocated',
  'ZA - South Africa': 'Not Allocated',
  'MX - Mexico': 'Not Allocated',
  'AR - Argentina': 'Not Allocated',
  'CL - Chile': 'Not Allocated',
  'CO - Colombia': 'Not Allocated',
  'PE - Peru': 'Not Allocated',
  'VE - Venezuela': 'Not Allocated',
  'KR - South Korea': 'Not Allocated',
  'SG - Singapore': 'Not Allocated',
  'MY - Malaysia': 'Not Allocated',
  'TH - Thailand': 'Not Allocated',
  'VN - Vietnam': 'Not Allocated',
  'ID - Indonesia': 'Not Allocated',
  'PH - Philippines': 'Not Allocated',
  'HK - Hong Kong': 'Not Allocated',
  'TW - Taiwan': 'Not Allocated',
  'SA - Saudi Arabia': 'Not Allocated',
  'AE - United Arab Emirates': 'Not Allocated',
  'IL - Israel': 'Not Allocated',
  'EG - Egypt': 'Not Allocated',
  'NG - Nigeria': 'Not Allocated',
  'KE - Kenya': 'Not Allocated',
  'GH - Ghana': 'Not Allocated',
  'DZ - Algeria': 'Not Allocated',
  'MA - Morocco': 'Not Allocated',
  'TN - Tunisia': 'Not Allocated',
  'SN - Senegal': 'Not Allocated',
  'CI - Ivory Coast': 'Not Allocated',
  'ET - Ethiopia': 'Not Allocated',
  'UG - Uganda': 'Not Allocated',
  'TZ - Tanzania': 'Not Allocated',
  'ZM - Zambia': 'Not Allocated',
  'ZW - Zimbabwe': 'Not Allocated',
  'BW - Botswana': 'Not Allocated',
  'NA - Namibia': 'Not Allocated',
  'MZ - Mozambique': 'Not Allocated',
  'AO - Angola': 'Not Allocated',
  'CD - Democratic Republic of the Congo': 'Not Allocated',
  'CM - Cameroon': 'Not Allocated',
  'ML - Mali': 'Not Allocated',
  'BF - Burkina Faso': 'Not Allocated',
  'NE - Niger': 'Not Allocated',
  'TG - Togo': 'Not Allocated',
  'BJ - Benin': 'Not Allocated',
  'LR - Liberia': 'Not Allocated',
  'SL - Sierra Leone': 'Not Allocated',
  'GW - Guinea-Bissau': 'Not Allocated',
  'GM - Gambia': 'Not Allocated',
  'GN - Guinea': 'Not Allocated',
  'MR - Mauritania': 'Not Allocated',
  'LY - Libya': 'Not Allocated',
  'SD - Sudan': 'Not Allocated',
  'SS - South Sudan': 'Not Allocated',
  'ER - Eritrea': 'Not Allocated',
  'DJ - Djibouti': 'Not Allocated',
  'SO - Somalia': 'Not Allocated',
  'KM - Comoros': 'Not Allocated',
  'MG - Madagascar': 'Not Allocated',
  'MU - Mauritius': 'Not Allocated',
  'SC - Seychelles': 'Not Allocated',
  'RW - Rwanda': 'Not Allocated',
  'BI - Burundi': 'Not Allocated',
  'MW - Malawi': 'Not Allocated',
  'LS - Lesotho': 'Not Allocated',
  'SZ - Eswatini': 'Not Allocated',
  'CV - Cape Verde': 'Not Allocated',
  'ST - Sao Tome and Principe': 'Not Allocated',
  'GQ - Equatorial Guinea': 'Not Allocated',
  'GA - Gabon': 'Not Allocated',
  'CG - Republic of the Congo': 'Not Allocated',
  'CF - Central African Republic': 'Not Allocated',
  'TD - Chad': 'Not Allocated',
  'EH - Western Sahara': 'Not Allocated',
 
};

export async function GET() {
  return NextResponse.json(initialGeoCodes);
}