import { NextResponse } from 'next/server';

export const initialAirlineCodes = {
  'AF - Air France': 'Not Allocated',
  'BA - British Airways': 'Not Allocated',
  'LH - Lufthansa': 'Not Allocated',
  'KL - KLM': 'Not Allocated',
  'AA - American Airlines': 'Not Allocated',
  'DL - Delta Air Lines': 'Not Allocated',
  'UA - United Airlines': 'Not Allocated',
  'SQ - Singapore Airlines': 'Not Allocated',
  'CX - Cathay Pacific': 'Not Allocated',
  'QF - Qantas': 'Not Allocated',
  'EK - Emirates': 'Not Allocated',
  'QR - Qatar Airways': 'Not Allocated',
  'EY - Etihad Airways': 'Not Allocated',
  'NH - All Nippon Airways': 'Not Allocated',
  'JL - Japan Airlines': 'Not Allocated',
  'KE - Korean Air': 'Not Allocated',
  'MU - China Eastern Airlines': 'Not Allocated',
  'CZ - China Southern Airlines': 'Not Allocated',
  'CA - Air China': 'Not Allocated',
  'BR - EVA Air': 'Not Allocated',
  'CI - China Airlines': 'Not Allocated',
  'TG - Thai Airways': 'Not Allocated',
  'MH - Malaysia Airlines': 'Not Allocated',
  'GA - Garuda Indonesia': 'Not Allocated',
  'VN - Vietnam Airlines': 'Not Allocated',
  'AI - Air India': 'Not Allocated',
  'AZ - Alitalia': 'Not Allocated',
  'IB - Iberia': 'Not Allocated',
  'AY - Finnair': 'Not Allocated',
  'SK - SAS - Scandinavian Airlines': 'Not Allocated',
  'OS - Austrian Airlines': 'Not Allocated',
  'LX - Swiss International Air Lines': 'Not Allocated',
  'SN - Brussels Airlines': 'Not Allocated',
  'TP - TAP Air Portugal': 'Not Allocated',
  'TK - Turkish Airlines': 'Not Allocated',
  'SU - Aeroflot': 'Not Allocated',
  'MS - EgyptAir': 'Not Allocated',
  'ET - Ethiopian Airlines': 'Not Allocated',
  'SA - South African Airways': 'Not Allocated',
  'NZ - Air New Zealand': 'Not Allocated',
  'VA - Virgin Australia': 'Not Allocated',
  'VS - Virgin Atlantic': 'Not Allocated',
  'AC - Air Canada': 'Not Allocated',
  'WS - WestJet': 'Not Allocated',
  'AM - Aeromexico': 'Not Allocated',
  'LA - LATAM Airlines': 'Not Allocated',
  'AV - Avianca': 'Not Allocated',
  'CM - Copa Airlines': 'Not Allocated',
  'G3 - Gol Transportes Aéreos': 'Not Allocated',
  'AD - Azul Brazilian Airlines': 'Not Allocated',
  'JJ - TAM Airlines': 'Not Allocated',
  'AR - Aerolineas Argentinas': 'Not Allocated',
  'UX - Air Europa': 'Not Allocated',
  'VY - Vueling': 'Not Allocated',
  'FR - Ryanair': 'Not Allocated',
  'U2 - easyJet': 'Not Allocated',
  'W6 - Wizz Air': 'Not Allocated',
  'DY - Norwegian Air Shuttle': 'Not Allocated',
  'PC - Pegasus Airlines': 'Not Allocated',
  'PS - Ukraine International Airlines': 'Not Allocated',
  'LO - LOT Polish Airlines': 'Not Allocated',
  'OK - Czech Airlines': 'Not Allocated',
  'RO - TAROM': 'Not Allocated',
  'JU - Air Serbia': 'Not Allocated',
  'OU - Croatia Airlines': 'Not Allocated',
  'BT - Air Baltic': 'Not Allocated',
  'FI - Icelandair': 'Not Allocated',
  'EI - Aer Lingus': 'Not Allocated',
  'MA - Malev Hungarian Airlines': 'Not Allocated',
 
};

export async function GET() {
  return NextResponse.json(initialAirlineCodes);
}